services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5000:8080"
  frontend:
    image: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=5001
    build: 
      context: ./Frontend/
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/src:/app/src
    ports:
      - "5001:3000"
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"