services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5000:8080"
  frontend:
    image: frontend
    build: 
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5001:3000"
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"